document:
  name: Linee guida per lo sviluppo e la definizione del modello nazionale di riferimento per i CERT regionali
  description: |
    Linee guida per lo sviluppo e la definizione del modello nazionale di riferimento per i CERT regionali
  tags:
    - CERT
    - sicurezza
